// Playground compile service, exposed as a Vite plugin.
//
// The page posts OCaml/mlx source here; this module writes it to a scratch dune
// project (playground/sandbox, gitignored), builds it with the requested
// backend and answers with the JavaScript produced plus its shape, so the
// preview frame knows whether to import it or run it as a <script>.
//
// Compiling arbitrary source is as privileged as running the toolchain by hand,
// so this is dev-server only — the published static site has no such endpoint.

import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SANDBOX_DIR = path.join(ROOT, "playground", "sandbox");
const SOURCE_FILE = path.join(SANDBOX_DIR, "main.mlx");

const GENERATED_BY = `; Generated by scripts/playground.mjs — the playground writes the editor
; buffer to main.mlx and builds this stanza, then deletes both. Not checked in.
`;

// The two backends, as the library documents them: the same core library and
// the same ppx either way, and only the dune stanza differs.
const BACKENDS = {
  melange: {
    label: "Melange",
    // <stanza dir>/<target>/<stanza dir>/<module>.js
    target: "playground/sandbox/output/playground/sandbox/main.js",
    format: "module",
    env: {},
    dune: `${GENERATED_BY}(melange.emit
 (target output)
 (modules main)
 (libraries reativa)
 (preprocess
  (pps reativa.mlx_ppx melange.ppx))
 (module_systems es6))
`,
  },
  jsoo: {
    label: "js_of_ocaml",
    target: "playground/sandbox/main.bc.js",
    format: "script",
    // Same gate the jsoo examples use, so a stray sandbox can never make a
    // plain `dune build` require js_of_ocaml.
    env: { REATIVA_JSOO: "enabled" },
    dune: `${GENERATED_BY}(executables
 (names main)
 (modes js)
 (enabled_if
  (= %{env:REATIVA_JSOO=} enabled))
 (libraries reativa reativa-jsoo)
 (preprocess
  (pps reativa.mlx_ppx)))
`,
  },
};

const DEFAULT_BACKEND = "melange";

const MAX_SOURCE_BYTES = 256 * 1024;
const BUILD_TIMEOUT_MS = 120_000;

// eslint-disable-next-line no-control-regex
const ANSI = new RegExp("\\u001b\\[[0-9;]*[A-Za-z]", "g");
const stripAnsi = (text) => text.replace(ANSI, "");

// Errors point at the scratch file; the editor only knows "your program".
const relabel = (text) =>
  stripAnsi(text).split("playground/sandbox/main.mlx").join("playground.mlx");

// One build at a time: dune locks _build, and the playground is single-user.
let queue = Promise.resolve();
const serialize = (task) => {
  const run = queue.then(task, task);
  queue = run.then(
    () => undefined,
    () => undefined,
  );
  return run;
};

let duneCommand = null;

/** Resolve how to invoke dune: directly if on PATH, else through opam. */
async function resolveDune() {
  if (duneCommand) return duneCommand;
  if (process.env.REATIVA_DUNE) {
    const parts = process.env.REATIVA_DUNE.split(" ").filter(Boolean);
    duneCommand = { command: parts[0], prefix: parts.slice(1) };
    return duneCommand;
  }
  const direct = await run("dune", ["--version"], 10_000).catch(() => null);
  duneCommand =
    direct && direct.code === 0
      ? { command: "dune", prefix: [] }
      : { command: "opam", prefix: ["exec", "--", "dune"] };
  return duneCommand;
}

function run(command, args, timeoutMs, env = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: ROOT,
      env: { ...process.env, ...env },
    });
    let stdout = "";
    let stderr = "";
    let timedOut = false;

    const timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
    }, timeoutMs);

    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", (error) => {
      clearTimeout(timer);
      reject(error);
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ code, stdout, stderr, timedOut });
    });
  });
}

/** Write the editor buffer into the scratch project. */
async function writeSandbox(code, backend) {
  await mkdir(SANDBOX_DIR, { recursive: true });
  await writeFile(path.join(SANDBOX_DIR, "dune"), backend.dune, "utf8");
  await writeFile(SOURCE_FILE, code.endsWith("\n") ? code : code + "\n", "utf8");
}

/**
 * Take the scratch stanza back out of the workspace once a run is done, so a
 * half-finished playground program can never fail an unrelated `dune build`.
 */
async function clearSandbox() {
  await rm(path.join(SANDBOX_DIR, "dune"), { force: true });
  await rm(SOURCE_FILE, { force: true });
}

/**
 * Compile a playground program.
 *
 * @param {string} code source of a complete .mlx program
 * @param {string} [name] backend to build with: "melange" (default) or "jsoo"
 * @returns {Promise<
 *   | {ok: true, js: string, format: string, backend: string, bytes: number}
 *   | {ok: false, stage: string, error: string}>}
 */
export async function compile(code, name = DEFAULT_BACKEND) {
  const backend = BACKENDS[name];
  if (!backend) {
    return {
      ok: false,
      stage: "input",
      error: `Unknown backend "${name}". Use one of: ${Object.keys(BACKENDS).join(", ")}.`,
    };
  }
  if (typeof code !== "string" || code.trim() === "") {
    return { ok: false, stage: "input", error: "Nothing to compile." };
  }
  if (Buffer.byteLength(code, "utf8") > MAX_SOURCE_BYTES) {
    return { ok: false, stage: "input", error: "Program is too large." };
  }

  return serialize(async () => {
    await writeSandbox(code, backend);
    try {
      const result = await buildSandbox(backend);
      return result.ok
        ? { ...result, backend: name, bytes: Buffer.byteLength(result.js, "utf8") }
        : result;
    } finally {
      await clearSandbox();
    }
  });
}

/** Build whatever is currently in the scratch project with one backend. */
async function buildSandbox(backend) {
  const { command, prefix } = await resolveDune();

  let build;
  try {
    build = await run(
      command,
      [...prefix, "build", backend.target],
      BUILD_TIMEOUT_MS,
      backend.env,
    );
  } catch (error) {
    if (error && error.code === "ENOENT") {
      return {
        ok: false,
        stage: "toolchain",
        error:
          `Could not run \`${command}\`. The playground needs the OCaml ` +
          "toolchain from this repo:\n\n  opam install . --deps-only --with-test\n\n" +
          "Set REATIVA_DUNE if dune lives somewhere unusual.",
      };
    }
    throw error;
  }

  if (build.timedOut) {
    return {
      ok: false,
      stage: "build",
      error: `The build timed out after ${BUILD_TIMEOUT_MS / 1000}s.`,
    };
  }
  if (build.code !== 0) {
    const output = relabel(build.stderr || build.stdout).trim();
    return {
      ok: false,
      stage: "build",
      error: withBackendHint(output, backend),
    };
  }

  const entry = path.join(ROOT, "_build", "default", backend.target);
  if (!existsSync(entry)) {
    return {
      ok: false,
      stage: "build",
      error:
        `The build reported success but ${backend.target} is missing.\n` +
        "Check that the backend's target layout still matches this script.",
    };
  }

  // js_of_ocaml already linked the runtime and every module into that one
  // script — it is what the browser runs, verbatim.
  if (backend.format === "script") {
    return { ok: true, js: await readFile(entry, "utf8"), format: backend.format };
  }

  // Melange emits one ES module per compilation unit; bundle them (plus the
  // reativa library and the Melange runtime) into a single importable file.
  try {
    const bundle = await esbuild.build({
      entryPoints: [entry],
      bundle: true,
      format: "esm",
      platform: "browser",
      write: false,
      logLevel: "silent",
      absWorkingDir: ROOT,
    });
    return { ok: true, js: bundle.outputFiles[0].text, format: backend.format };
  } catch (error) {
    return {
      ok: false,
      stage: "bundle",
      error: stripAnsi(String(error && error.message ? error.message : error)),
    };
  }
}

/** A missing js_of_ocaml backend is an install away, so say which one. */
function withBackendHint(output, backend) {
  const text = output || "The build failed without producing a message.";
  if (backend.env.REATIVA_JSOO && /reativa-jsoo|js_of_ocaml/.test(text)) {
    return (
      text +
      "\n\nThe js_of_ocaml backend lives in its own package:\n\n" +
      "  opam install reativa-jsoo js_of_ocaml"
    );
  }
  return text;
}

function send(res, status, payload) {
  const body = JSON.stringify(payload);
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");
  res.end(body);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on("data", (chunk) => {
      size += chunk.length;
      if (size > MAX_SOURCE_BYTES * 2) {
        reject(new Error("Request body too large."));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

/** Connect-style middleware backing the playground endpoints. */
export async function handle(req, res) {
  const url = (req.url || "").split("?")[0];

  if (url === "/__playground/status") {
    // The page reads the backend list from here, so adding one is a
    // server-side change only.
    send(res, 200, {
      ok: true,
      backends: Object.entries(BACKENDS).map(([id, backend]) => ({
        id,
        label: backend.label,
      })),
    });
    return true;
  }

  if (url === "/__playground/compile") {
    if (req.method !== "POST") {
      send(res, 405, { ok: false, stage: "input", error: "Use POST." });
      return true;
    }
    try {
      const raw = await readBody(req);
      const parsed = JSON.parse(raw || "{}");
      const result = await compile(parsed.code, parsed.backend);
      send(res, 200, result);
    } catch (error) {
      send(res, 200, {
        ok: false,
        stage: "server",
        error: String(error && error.message ? error.message : error),
      });
    }
    return true;
  }

  return false;
}

/** Vite plugin: mounts the playground endpoints on the dev server. */
export function playgroundPlugin() {
  return {
    name: "reativa-playground",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        handle(req, res).then(
          (handled) => {
            if (!handled) next();
          },
          (error) => next(error),
        );
      });
    },
  };
}

export default playgroundPlugin;
