// Playground compile service.
//
// The playground page posts OCaml/mlx source here; this module writes it into
// a scratch dune project (playground/sandbox, gitignored), builds it with
// Melange and bundles the emitted ES modules with esbuild. The response is a
// single JavaScript module the browser imports inside the preview frame.
//
// It is exposed as a Vite plugin so `npm run playground` (and `npm run
// docs:dev`) is all you need. Compiling arbitrary source is as privileged as
// running the toolchain by hand, so it is a dev-server-only feature — the
// static site published to Pages has no such endpoint.

import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SANDBOX_DIR = path.join(ROOT, "playground", "sandbox");
const SOURCE_FILE = path.join(SANDBOX_DIR, "main.mlx");

// Where dune drops the emitted entry: <stanza dir>/<target>/<stanza dir>/<module>.js
const BUILD_TARGET = "playground/sandbox/output/playground/sandbox/main.js";
const ENTRY_FILE = path.join(ROOT, "_build", "default", BUILD_TARGET);

const SANDBOX_DUNE = `; Generated by scripts/playground.mjs — the playground writes the editor
; buffer to main.mlx and builds this stanza. Not checked in.
(melange.emit
 (target output)
 (modules main)
 (libraries reativa)
 (preprocess
  (pps reativa.mlx_ppx melange.ppx))
 (module_systems es6))
`;

const MAX_SOURCE_BYTES = 256 * 1024;
const BUILD_TIMEOUT_MS = 120_000;

// eslint-disable-next-line no-control-regex
const ANSI = new RegExp("\\u001b\\[[0-9;]*[A-Za-z]", "g");
const stripAnsi = (text) => text.replace(ANSI, "");

// Errors point at the scratch file; the editor only knows "your program".
const relabel = (text) =>
  stripAnsi(text).split("playground/sandbox/main.mlx").join("playground.mlx");

// One build at a time: dune locks _build, and the playground is single-user.
let queue = Promise.resolve();
const serialize = (task) => {
  const run = queue.then(task, task);
  queue = run.then(
    () => undefined,
    () => undefined,
  );
  return run;
};

let duneCommand = null;

/** Resolve how to invoke dune: directly if on PATH, else through opam. */
async function resolveDune() {
  if (duneCommand) return duneCommand;
  if (process.env.REATIVA_DUNE) {
    const parts = process.env.REATIVA_DUNE.split(" ").filter(Boolean);
    duneCommand = { command: parts[0], prefix: parts.slice(1) };
    return duneCommand;
  }
  const direct = await run("dune", ["--version"], 10_000).catch(() => null);
  duneCommand =
    direct && direct.code === 0
      ? { command: "dune", prefix: [] }
      : { command: "opam", prefix: ["exec", "--", "dune"] };
  return duneCommand;
}

function run(command, args, timeoutMs) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd: ROOT, env: process.env });
    let stdout = "";
    let stderr = "";
    let timedOut = false;

    const timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
    }, timeoutMs);

    child.stdout.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", (error) => {
      clearTimeout(timer);
      reject(error);
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ code, stdout, stderr, timedOut });
    });
  });
}

/** Write the editor buffer into the scratch project. */
async function writeSandbox(code) {
  await mkdir(SANDBOX_DIR, { recursive: true });
  await writeFile(path.join(SANDBOX_DIR, "dune"), SANDBOX_DUNE, "utf8");
  await writeFile(SOURCE_FILE, code.endsWith("\n") ? code : code + "\n", "utf8");
}

/**
 * Take the scratch stanza back out of the workspace once a run is done, so a
 * half-finished playground program can never fail an unrelated `dune build`.
 */
async function clearSandbox() {
  await rm(path.join(SANDBOX_DIR, "dune"), { force: true });
  await rm(SOURCE_FILE, { force: true });
}

/**
 * Compile a playground program.
 *
 * @param {string} code source of a complete .mlx program
 * @returns {Promise<{ok: true, js: string} | {ok: false, stage: string, error: string}>}
 */
export async function compile(code) {
  if (typeof code !== "string" || code.trim() === "") {
    return { ok: false, stage: "input", error: "Nothing to compile." };
  }
  if (Buffer.byteLength(code, "utf8") > MAX_SOURCE_BYTES) {
    return { ok: false, stage: "input", error: "Program is too large." };
  }

  return serialize(async () => {
    await writeSandbox(code);
    try {
      return await buildSandbox();
    } finally {
      await clearSandbox();
    }
  });
}

/** Build whatever is currently in the scratch project and bundle the result. */
async function buildSandbox() {
  const { command, prefix } = await resolveDune();

  let build;
  try {
    build = await run(command, [...prefix, "build", BUILD_TARGET], BUILD_TIMEOUT_MS);
  } catch (error) {
    if (error && error.code === "ENOENT") {
      return {
        ok: false,
        stage: "toolchain",
        error:
          `Could not run \`${command}\`. The playground needs the OCaml ` +
          "toolchain from this repo:\n\n  opam install . --deps-only --with-test\n\n" +
          "Set REATIVA_DUNE if dune lives somewhere unusual.",
      };
    }
    throw error;
  }

  if (build.timedOut) {
    return {
      ok: false,
      stage: "build",
      error: `The build timed out after ${BUILD_TIMEOUT_MS / 1000}s.`,
    };
  }
  if (build.code !== 0) {
    const output = relabel(build.stderr || build.stdout).trim();
    return {
      ok: false,
      stage: "build",
      error: output || "The build failed without producing a message.",
    };
  }
  if (!existsSync(ENTRY_FILE)) {
    return {
      ok: false,
      stage: "build",
      error:
        `The build reported success but ${BUILD_TARGET} is missing.\n` +
        "Check that the Melange target layout still matches this script.",
    };
  }

  // Melange emits one ES module per compilation unit; bundle them (plus the
  // reativa library and the Melange runtime) into a single importable file.
  try {
    const bundle = await esbuild.build({
      entryPoints: [ENTRY_FILE],
      bundle: true,
      format: "esm",
      platform: "browser",
      write: false,
      logLevel: "silent",
      absWorkingDir: ROOT,
    });
    return { ok: true, js: bundle.outputFiles[0].text };
  } catch (error) {
    return {
      ok: false,
      stage: "bundle",
      error: stripAnsi(String(error && error.message ? error.message : error)),
    };
  }
}

function send(res, status, payload) {
  const body = JSON.stringify(payload);
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");
  res.end(body);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on("data", (chunk) => {
      size += chunk.length;
      if (size > MAX_SOURCE_BYTES * 2) {
        reject(new Error("Request body too large."));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

/** Connect-style middleware backing the playground endpoints. */
export async function handle(req, res) {
  const url = (req.url || "").split("?")[0];

  if (url === "/__playground/status") {
    send(res, 200, { ok: true });
    return true;
  }

  if (url === "/__playground/compile") {
    if (req.method !== "POST") {
      send(res, 405, { ok: false, stage: "input", error: "Use POST." });
      return true;
    }
    try {
      const raw = await readBody(req);
      const parsed = JSON.parse(raw || "{}");
      const result = await compile(parsed.code);
      send(res, 200, result);
    } catch (error) {
      send(res, 200, {
        ok: false,
        stage: "server",
        error: String(error && error.message ? error.message : error),
      });
    }
    return true;
  }

  return false;
}

/** Vite plugin: mounts the playground endpoints on the dev server. */
export function playgroundPlugin() {
  return {
    name: "reativa-playground",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        handle(req, res).then(
          (handled) => {
            if (!handled) next();
          },
          (error) => next(error),
        );
      });
    },
  };
}

export default playgroundPlugin;
